### ISSUE TITLE
Remove letterboxing from video thumbnails

### ISSUE THREAD

**Issue by paulyoung** [jonnor/imgflo#50]
It would be great if a component could process this image and intelligently remove the black bars from the top and bottom.

![hqdefault](https://cloud.githubusercontent.com/assets/84700/3772188/ab7c8a3e-18fc-11e4-98f8-6ad3ce4537e7.jpg)

Source: http://img.youtube.com/vi/Dg3lVNcQlhc/hqdefault.jpg

**Comment by jonnor** [comment]
Could be that the new saliency capabilities provided by https://github.com/the-grid/gmr-saliency is enough for this

**Comment by jonnor** [comment]
Closing as out-of-scope, imgflo API client needs to detect and specify appropriate cropping.
