### ISSUE TITLE
proxy/cache GIF files

### ISSUE THREAD

**Issue by forresto** [jonnor/imgflo#85]
Before full processing support (#49) we need to be able to proxy/cache GIF files so that chrome and sites don't get mixed-content warnings.

Maybe a new `proxy` graph (or drop arguments in `passthrough`) that we can force in imgflo-url (instead of [skipping imgflo](https://github.com/the-grid/imgflo-url/blob/889a9904dd5673eb4ef40297f77e3fa094170626/index.coffee#L36)).

**Comment by forresto** [comment]
Mixed content warnings getting more prominent. 

![screenshot_2015-09-06-00-34-09 2](https://cloud.githubusercontent.com/assets/395307/9707188/1b89b538-54cd-11e5-8489-71ee5184c210.png)

**Comment by paulyoung** [comment]
:facepunch: bump

**Comment by paulyoung** [comment]
This presents an issue now on iOS 9. Any requests for gifs that are being served over http will be blocked by the OS.

**Comment by jonnor** [comment]
Yeah, bumped in pri. Maybe later this week.

**Comment by paulyoung** [comment]
:raised_hands:

**Comment by forresto** [comment]
ff ![ff](https://cloud.githubusercontent.com/assets/395307/10401936/2ae64f50-6e90-11e5-8d91-6ca68447349b.png)
chrome ![chrome](https://cloud.githubusercontent.com/assets/395307/10401937/2ae79acc-6e90-11e5-9614-1485ac415a13.png)
only when scrolled down to a http gif

**Comment by jonnor** [comment]
Getting messages of XHRs being blocked in modern Chrome now:

```Mixed Content: The page at 'https://api.thegrid.io/solution/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2F….9.95%2Ftaylor.js/2d6c33046f50d53780b27742c716dfc8/bergie-today/index.html' was loaded over HTTPS, but requested an insecure image 'http://virtualschool.edu/cox/pub/PSIR/PSIR4.gif'. This request has been blocked; the content must be served over HTTPS.```

Though this issue should actually be in https://github.com/jonnor/imgflo-server
