### ISSUE TITLE
rotation units

### ISSUE THREAD

**Issue by forresto** [jonnor/imgflo#86]
When imgflo supports [rotation](https://github.com/the-grid/grid-chrome/issues/142), what units will make things easy? exif is `[1,6,3,8]` for `[0,90,180,270]` ... I'll set degrees unless there is another preference.

**Comment by jonnor** [comment]
Degrees, which would be a scalar in range `[0-360`
Exif values in general are more 'orientation' (also includes things like mirroring) that rotation, and is an enumerated set.
